# Image Dockerfile is your notebook
# Install Java
FROM eclipse-temurin:23-jdk

LABEL maintainer="zakcove" 

## Build the application
# Create directory /app and change directory into /app
WORKDIR /app

# Copy files over src dest
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src src

# Package the application
RUN chmod a+x ./mvnw && ./mvnw package -Dmaven.test.skip=true

# If build is successful, then the jar is in ./target/login-0.0.1-SNAPSHOT.jar 

## How to run the application
# ENV SERVER_PORT=8080
# for Railway
ENV PORT=8080
ENV SPRING.DATASOURCE.URL=mysql://viaduct.proxy.rlwy.net:54885/railway SPRING.DATASOURCE.USERNAME=root SPRING.DATASOURCE.PASSWORD=
ENV SPRING.DATA.MONGODB.HOST=mongodb+srv://userOne:userOne@cluster1.87r5q.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1

# What port does the application need
# EXPOSE ${SERVER_PORT}
EXPOSE ${PORT}

# Run the application
ENTRYPOINT SERVER_PORT=${PORT} java -jar target/movies-0.0.1-SNAPSHOT.jar 